# Generated by Django 5.2.7 on 2025-11-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', '관리자'), ('BORROWER', '차주'), ('LENDER', '대주')], default='BORROWER', max_length=20),
        ),
    ]
