# Generated by Django 5.2.7 on 2025-11-10 12:47

import django.db.models.deletion
import submissions.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(help_text='신청 제목 (예: 2024년 3분기 심의신청)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='간단한 메모/설명')),
                ('status', models.CharField(choices=[('DRAFT', '임시저장'), ('SUBMITTED', '제출완료'), ('UNDER_REVIEW', '심사중'), ('COMPLETED', '완료')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(help_text='신청을 올린 차주', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=submissions.models.submission_upload_path)),
                ('original_name', models.CharField(help_text='업로드 당시 파일 이름', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='submissions.submission')),
            ],
        ),
    ]
