# Generated by Django 5.2.7 on 2025-11-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='net_income',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='당기순이익(원)', max_digits=16, null=True),
        ),
    ]
