# Generated by Django 5.2.7 on 2025-11-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('DRAFT', '임시저장'), ('SUBMITTED_REVIEW', '제출완료 및 검토'), ('REVISION_REQUESTED', '수정요청'), ('REVISED_REVIEW', '수정완료 및 검토'), ('FINALIZED', '최종확정')], default='DRAFT', max_length=30),
        ),
    ]
