# Generated by Django 5.2.7 on 2025-11-15 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_alter_submission_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('COMMENT', '일반코멘트'), ('REQUEST', '수정요청'), ('STATUS_CHANGE', '상태변경')], max_length=20)),
                ('field_name', models.CharField(default='general', help_text='예: net_income, general 등', max_length=50)),
                ('message', models.TextField(blank=True, help_text='수정요청/코멘트/상태변경에 대한 설명')),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', '임시저장'), ('SUBMITTED_REVIEW', '제출완료 및 검토'), ('REVISION_REQUESTED', '수정요청'), ('REVISED_REVIEW', '수정완료 및 검토'), ('FINALIZED', '최종확정')], max_length=30, null=True)),
                ('to_status', models.CharField(blank=True, choices=[('DRAFT', '임시저장'), ('SUBMITTED_REVIEW', '제출완료 및 검토'), ('REVISION_REQUESTED', '수정요청'), ('REVISED_REVIEW', '수정완료 및 검토'), ('FINALIZED', '최종확정')], max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_events', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='submissions.submission')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
