# Generated by Django 5.2.7 on 2025-11-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_submissionevent_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('DRAFT', '임시저장'), ('IN_REVIEW', '검토 중'), ('REVISION_REQUIRED', '수정요청'), ('FINALIZED', '최종확정')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='submissionevent',
            name='from_status',
            field=models.CharField(blank=True, choices=[('DRAFT', '임시저장'), ('IN_REVIEW', '검토 중'), ('REVISION_REQUIRED', '수정요청'), ('FINALIZED', '최종확정')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='submissionevent',
            name='to_status',
            field=models.CharField(blank=True, choices=[('DRAFT', '임시저장'), ('IN_REVIEW', '검토 중'), ('REVISION_REQUIRED', '수정요청'), ('FINALIZED', '최종확정')], max_length=30, null=True),
        ),
    ]
