# Generated by Django 5.2.7 on 2025-11-16 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_alter_submission_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='내부용 필드 이름 (예: net_income)', max_length=100)),
                ('label', models.CharField(help_text='화면에 표시할 라벨 (예: 당기순이익(원))', max_length=200)),
                ('value', models.TextField(blank=True, help_text='파일에서 읽어온 값(문자열 형태)')),
                ('data_type', models.CharField(choices=[('TEXT', '텍스트'), ('NUMBER', '숫자')], default='TEXT', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='화면에 표시될 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='submissions.submission')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
