# Generated by Django 5.2.7 on 2025-11-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_submissionfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='net_income',
        ),
        migrations.AlterField(
            model_name='submissionevent',
            name='field_name',
            field=models.CharField(default='general', help_text='예: net_income, general 등 (지금은 일반용으로만 사용)', max_length=50),
        ),
    ]
