# Generated by Django 5.2.7 on 2025-11-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_submission_normalized_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='normalized_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='차주가 수정한 값(키 경로 → 값)'),
        ),
    ]
